#!/bin/sh /etc/rc.common

START=99
STOP=99
USE_PROCD=1

start_service() {
			 echo "Starting Application RouterAuditApp"
	        /root/RouterAuditAppComponent/RouterAuditApp > /dev/null 2>&1 &
}

stop_service() {
			echo "Stopping Application RouterAuditApp"
			killall -9 "RouterAuditApp" > /dev/null 2>&1    
}
