#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2015 OpenWrt.org

START=99
USE_PROCD=1

BIN="/root/RouterAuditAppComponent/RouterAuditApp"

start_service()
{
	procd_open_instance
	procd_set_param command $BIN
	mv /root/RouterAuditAppComponent/Monitor_RouterAuditApp /etc/monit.d/
	procd_close_instance
	
}

# reload_service()
# {
#     uci set connectionDiagnostics.general.running="1"
#     uci commit connectionDiagnostics
#     enable=$(uci get connectionDiagnostics.general.enable)
#     if [ $enable -eq 1 ]
#     then
#         /bin/connectionDiagnostics &
#     fi
# }

stop_service()
{
	mv /etc/monit.d/Monitor_RouterAuditApp /root/RouterAuditAppComponent/
    pid=$(pgrep -f "/root/RouterAuditAppComponent/RouterAuditApp")
	kill -TERM "$pid" &
}
