#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2015 OpenWrt.org

START=99
USE_PROCD=1

BIN="/root/Device_Health"
Monitscript="/usr/bin/monit -I"

start_service() {

    #procd_open_instance
    #procd_set_param command $BIN
    #procd_set_param respawn
    #mv /root/Monitor_HealthMoniterApp /etc/monit.d/
    #procd_close_instance

    #if pgrep -f "$Monitscript" > /dev/null; then
        #echo "monit daemon already running"
    #else
        #/etc/monit start
    #fi
    
    /root/Device_Health > /dev/null 2>&1 &
    
}

stop_service() {

        mv /etc/monit.d/Monitor_HealthMoniterApp /root/

        pid=$(pgrep -f "$BIN")
        [ -n "$pid" ] && kill -TERM "$pid"
        #echo "Stopping Application Device_Health"
			#killall -9 "Device_Health" > /dev/null 2>&1
    
}
