#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

UpdateConfigScript="/root/InterfaceManager/script/vpn/ipip/IPIPconfig.sh"
DeleteConfigScript="/root/InterfaceManager/script/vpn/ipip/DeleteIPIPConfig.sh"

case "$1" in
    list)
        echo '{"configureipip":{},"delete":{}}'
        ;;
    call)
        case "$2" in
                    configureipip)
                            response=$($UpdateConfigScript)
							if [ "$?" -ne 0 ]
                            then
								echo "{\"code\":1,\"output\":\"FAILURE : IPIP Configuration Update\"}"
                            else
                               	echo "{\"code\":0,\"output\":\"SUCCESS : IPIP Configuration Update\"}"
                            fi
                                                                                 
                            ;;    
                            
                      delete)
                            response=$($DeleteConfigScript)
							if [ "$?" -ne 0 ]
                            then
								echo "{\"code\":1,\"output\":\"FAILURE : IPIP Configuration Update\"}"
                            else
                               	echo "{\"code\":0,\"output\":\"SUCCESS : IPIP Configuration Update\"}"
                            fi
                                                                                 
                            ;;         
          
		             *)
		                    echo '{"code":"1","output":"invalid method"}'
		                    exit 1
		                    ;;
     
        esac #appmanager method
        ;;
esac # ubus method

exit 0
