#!/bin/sh
. /usr/share/libubox/jshn.sh
. /lib/functions.sh

DHCPScript="/root/Device_health/dhcp_neighbors.sh"

case "$1" in
    list)
         echo '{"configure":{}}'
        ;;
    call)
        case "$2" in
                    configure)
                            response=$($DHCPScript)
							if [ "$?" -ne 0 ]
                            then
								echo "{\"code\":1,\"output\":\"FAILURE : Read DHCP Leases\"}"
                            else
                               	echo "{\"code\":0,\"output\":\"SUCCESS :  Read DHCP Leases\"}"
                            fi
                                                                                 
                            ;;
            *)
                echo '{"code":1,"output":"invalid method"}'
                exit 1
                ;;
        esac
        ;;
esac

exit 0
