#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh


case "$1" in
    list)
        echo '{"disable":{}}'
        ;;
    call)
        case "$2" in
                    disable)
                            board_name=$(cat /tmp/sysinfo/board_name)
							if echo "$board_name" | grep -qE "(IE44)";
							then
									echo 0 > /sys/class/gpio/gpio3/value
									pid=$(pgrep -f "/bin/Watchdog_Enable_Disable")
									kill -9 $pid
									Disablestatus=$(cat /sys/class/gpio/gpio3/value)
							else
									echo 0 > /sys/class/gpio/gpio36/value
									pid=$(pgrep -f "/bin/Watchdog_Enable_Disable")
									kill -9 $pid
									Disablestatus=$(cat /sys/class/gpio/gpio36/value)
							fi
							                                                    
                            ;;                
                    *)
                    echo '{"code":"1","output":"invalid method"}'
                    exit 1
        esac #appmanager method
        ;;
esac # ubus method

exit 0
