#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

UpdateConfigScript="/root/InterfaceManager/script/vpn/gre/Greconfig.sh"
DeleteConfigScript="/root/InterfaceManager/script/vpn/gre/DeleteGreconfig.sh"
Gre_status="/root/InterfaceManager/script/vpn/gre/grestatus.sh"
case "$1" in
    list)
        echo '{"configuregre":{},"delete":{}}'
        ;;
    call)
        case "$2" in
                    configuregre)
                             Enable_gre=$(uci get vpnconfig1.general.enablegre)
                             if [ "$Enable_gre" = "1" ]
                            then
                               sed -i '/grestatus.sh/d' /etc/crontabs/root
                               echo "*/1 * * * * /root/InterfaceManager/script/GRE/grestatus.sh" >> /etc/crontabs/root  
                               /etc/init.d/cron restart 
                               response=$($UpdateConfigScript)
                               sleep 3
                               response=$($Gre_status)
			                    echo "{\"code\":1,\"output\":\"SUCCESS : GRE Configuration Update\"}"

                            else
                              response=$($Gre_status)
                              response=$($DeleteConfigScript)
                              sed -i '/grestatus.sh/d' /etc/crontabs/root
                              echo "{\"code\":0,\"output\":\"SUCCESS : GRE Configuration Update\"}"
                            fi						                                                                                                                                     
                            ;; 
                            
                                
                      delete)
                            response=$($DeleteConfigScript)
							if [ "$?" -ne 0 ]
                            then
								echo "{\"code\":1,\"output\":\"FAILURE : GRE Configuration Update\"}"
                            else
                               	echo "{\"code\":0,\"output\":\"SUCCESS : GRE Configuration Update\"}"
                            fi
                                                                                 
                            ;;                                                              
                    
		             *)
		                    echo '{"code":"1","output":"invalid method"}'
		                    exit 1
		                    ;;
     
        esac #appmanager method
        ;;
esac # ubus method

exit 0
