#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2015 OpenWrt.org

START=99
USE_PROCD=1

BIN="/root/TCPSLAVE/TCP_Slave_Utility_project"

start_service()
{
	enable=$(uci get tcpconfig.tcpconfig.enabletcp)
	if [ "$enable" = "1" ]
	then
       		procd_open_instance
        	procd_set_param command $BIN
        	procd_close_instance
		sh /bin/modem.sh & > dev/null 
	else
		 pid=$(pgrep -f "/root/TCPSLAVE/TCP_Slave_Utility_project")
	        kill -TERM "$pid" > /dev/null 2>&1
	fi

}

stop_service()
{
    pid=$(pgrep -f "/root/TCPSLAVE/TCP_Slave_Utility_project")
	kill -TERM "$pid" > /dev/null 2>&1
}
