#!/bin/sh

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

DO_Script="/bin/DO_pins_Cal.sh"

case "$1" in
    list)
        echo '{"configure":{}}'
        ;;
        
    call)
        case "$2" in
            configure)
                read -r input
                json_load "$input" 2>/dev/null

                # Run DO script properly
                response=$($DO_Script 2>&1)
                exit_code=$?

                if [ "$exit_code" -ne 0 ]; then
                    echo '{"code":1,"output":"FAILURE: Configuration could not be applied."}'
                else
                    # Proper JSON variable expansion
                    echo "{\"code\":0,\"output\":$response}"
                fi
                ;;
                
            *)
                echo '{"code":1,"output":"Invalid method."}'
                exit 1
                ;;
        esac
        ;;
esac

exit 0
